name: Role
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Adicionamos o gerador de ícones aqui
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- CONFIGURAÇÃO DOS ÍCONES ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Certifique-se que a imagem 'icone_novo.png' está na pasta mobile/ (ao lado deste arquivo)
  image_path: "icone_novo.png"
  min_sdk_android: 21
  # Configuração para ícone adaptativo (Android 8+)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icone_novo.png"